(define-module (arnytron greetings)
  #:version (0 0 1)
  #:export (greetings)
)

(define greetings '(
 (#t "2011-04-05" "salut nouveaux geeks infiltrés en immersion dans la nouvelle chaleur des nuits du vice d'internet" ())
 (#t "2011-04-08" "salut Johnny, Delon et Depardieu!" ("***ArnY devient vraiment vulgaire"))
 (#t "2011-04-10" "salut les enfants de coeurs traffiquant d'ostie dans la cours de récrée avec un tshirt \"god made me do it\"" ())
 (#t "2011-04-11" "salut les cloud computés" ())
 (#t "2011-04-20" "salut les nabots culs de jate champions du monde de natation" ())
 (#t "2011-04-22" "salut les nouveaux hackers nus en immersion dans la chaleur du net russe des nuits de la jet set parsienne sur la côte d'azur dans les maisons close en pleine action exclusif d'enquête people dans la drogue" ("ArnY: exclusive, pardon" "Balise: ArnY: c'est un peu tiré par les cheveux" "ArnY: j'ai oublié de rajouter \"inedit IRC\" pourtant!" "Feufochmar: je pense que Arny devrait immiter le style de Proust la prochaine fois, mais ça risque d'être tl;dr" "***ArnY va plutot faire du Duras, c'est compatible avec la longueur soporifique"))
 (#f "2011-04-23" "איר כאָופּט אַ באַליידיקונג, האַ, האַהאַ!" ("dibalo: tu t'es converti ?"))
 (#t "2011-04-29" "salut jeunes gens beaux et interessants que vous êtes!" ("Craglu: (SK va hurler au fake)" "SK: ouais fake"))
 (#t "2011-05-01" "salut les tr..Ah? pardon, mauvais numéro!" ("(ArnY quitte le salon)" "(Arny revient)" "SK: un point pour l'originalité quand meme"))
 (#t "2011-05-05" "salut les tranches de hareng saure saumatres!" ("dibalo: salut l'utilisateur de bebop"))
 (#t "2011-05-21" "salut cosmonautes en culottes courtes!" ("Olaf-: Mmmh, un petit 1/10 là" "dibalo: t'as trahi tes fan qui croyaient en toi !" "ArnY: je vous emmerde!" "..."))
 (#t "2011-05-28" "salut les moisis du kiki!" ("Olaf-: Tu veux goûter ?" "ArnY: non merci, je viens de finir de manger"))
 (#t "2011-05-29" "salut les zoophiles pervers producteurs de miel et eleveurs de fourmiliers!" ("Olaf-: Ah, un bon 8/10 là ArnY"))
 (#t "2011-05-31" "salut les esquimos naines actrices de porno, grandes consommatrices de baumes pour les lèvres" ("companion_cube: ôO"))
 (#t "2011-06-03" "salut les anorexiques couverts d'huile d'olive dansant le smurf aux puces de Saint Ouen!" ("Craglu: ArnY : stoi le saint toin"))
 (#t "2011-06-09" "bonsoir les abcès dentaires purulents dans la bouche d'une peripatéticienne cocainomane travaillant dans les toilettes publiques de Barbès" ("Olaf-: Mouais, en précisant Barbès ça réduit fortement les personnes concernées là" "shawn: avec abcès tu te sentais concerné ?"))
 (#t "2011-06-17" "salut les mémés inuits en bikini faisant du skate sur des biscottes en fontes!" ("Olaf-: Mmmh, un petit 6." "Craglu: c’est companion_cube le petit suisse"))
 (#t "2011-06-21" "salut les boudins à face de pizza membrés comme des saucisses de strasbourgs" ("ArnY: saucisses à apéro, bien sur" "***ArnY ne voudrait pas vous flatter inutilement"))
 (#t "2011-06-22" "salut les putois priapiques" ("Olaf-: Ah, simple et puissant, 9/10 ArnY" "SK: < Olaf-> Ah, simple et puissant, 9/10 ArnY <= c'est tout ArnY ca"))
 (#t "2011-06-23" "salut les anus de chameaux dilatés souffrant de diarhée explosive pleine de parasites purulents" ("SK: tain on arrive tous les soirs en synchro" "ArnY: les grands esprits..." "ArnY: ou les grand sexes, peut etre"))
 (#t "2011-06-27" "salut les vers solitaires atteint de priapisme soudain!" ("companion_cube: ça m'a l'air physiologiquement intriguant"))
 (#t "2011-06-28" "salut les snipers en embuscade pris de diarhée soudaine" ())
 (#t "2011-07-01" "salut les désanussés mous du gland!" ())
 (#t "2011-07-03" "salut les bites crochues" ("Craglu: 2/10" "Olaf-: ArnY: C'est pour mieux forcer les femmes, demande à DSK" "***Craglu n’a pas la bite crochue mais en tire-bouchon"))
 (#t "2011-07-04" "salut les vampires naines de poche!" ())
 (#t "2011-07-05" "salut les clodos roux et nus faisant la manche dans le metro le dimanche matin!" ("Balise: salut le non-encerclé" "ArnY: non au cerclage!" "MFX: oui au bondage ?" "dibalo: hé ho ! pas d'insultes ! je ne suis pas roux !"))
 (#t "2011-07-06" "salut les graines germées inventées par un vampire scatophile!" ("neoXL: there should be a @shitoldarnysays twitter account" "companion_cube: ou alors un flux Craglu^W rss" "rbs: ou un site web" "rbs: (avec flux rss)"))
 (#t "2011-07-08" "salut les mal aux culs malotrus malhonnètes mollardés molasons!" ("Craglu: molaçons !" "SK: houlala" "SK: avec des allit?rations maintenant !" "ArnY: Craglu: c'est les mal aux culs aussi" "ArnY: +toi" "Craglu: SK : non disons que là j’ai 2 cercles, et l’un est strictement inclus dans l’autre" "ArnY: Craglu: tu relèves molaçons mais pas maux de cul?" "Craglu: ça dépend de comment tu considères mal au cul" "Craglu: les maux" "Craglu: ou les gens qui ont mal au cul" "ArnY: les \"mal au cul\" dans ce cas" "Craglu: oué" "ArnY: mais pas les mal aux culs :)"))
 (#t "2011-07-23" "salut les naines obsèses skatebordeuses par nécessité!" ("companion_cube: retourne bouquiner, toi" "Craglu: stoi le nain cessiteux" "Craglu: mmm, nez cessité, mmm, lunettes\xa0?"))
 (#t "2011-07-26" "salut les pisciculteurs scatophiles au gland lumineux!" ())
 (#t "2011-07-30" "Salut les montpellierens vendeurs de machine à coudre sur Internet !" ())
 (#t "2011-08-03" "salut mes gentils amis sur lesquels je compte beaucoup et dont mon estime pour eux est sans limites, je vous aime!" ("tripa: et a nous, tu nous dirais pas bonjour?" "Olaf-: fake!"))
 (#t "2011-08-04" "salut les phallus machos mou du genou!" ("ArnY: bon, ca sert à rien que je me décarcasse à vous insulter si personne n'écoute!" "***Olaf- jette une carcasse de voiture calcinée sur ArnY" "ArnY: c'est pas encore le nouvel an!" "ArnY: respectons les traditions, quand même!"))
 (#t "2011-08-07" "Salut les tout petits gens rikikis dans mon telefon!" ("Craglu: bof" "ArnY: Je vais ecrire un roman non plus"))
 (#t "2011-08-10" "salut les gay internautes sadomaso fan d'Apple!" ("***ArnY n'etait point inspirés ce soir"))
 (#t "2011-08-19" "salut les goths albinos glauques et odorants jouant à cache cache sur une piste de ski en plein hiver!" ())
 (#t "2011-08-22" "salut gros routiers obsèses et huilé en bikinis" ("Craglu: salut l'orignal"))
 (#t "2011-08-24" "salut les motocrottes à la place nudistes!" ("ArnY: plage!" "Craglu: salut le motonudiste" "ArnY: ah non, moi c'est motocrottiste" "Craglu: tu t’auto-crottes\xa0?" "Craglu: c’est moche l’incontinence"))
 (#t "2011-08-29" "salut les garagistes onanistes ayant pignon sur rue à Pigale!" ())
 (#t "2011-08-30" "salut les ouistitis rikikis du zizi!" ("Palats: stoi" "Simplet: bwêêêêk"))
 (#t "2011-08-31" "salut les bucherons sodomites rếvant de troncs à raboter!" ("Craglu: c’est toi le ế" "Craglu: tu vas te faire insulter par SK si tu fais d’autres cochoncetés" "SK: ?" "shawn: c'est censé être quoi le ?" "companion_cube: comme '!', mais en différent" "Craglu: shawn : il a fait ^ + é au lieu de ^ + e" "Craglu: du coup ça fait ế au lieu de ê"))
 (#t "2011-09-08" "salut les grecs!" ("rbs: tu viens te faire voir chez les grecs ?" "rbs: mmh d'ailleurs c'est ptet plutot foutre que voir..." "rbs: ça parrait plus logique"))
 (#t "2011-09-11" "Salut la League of Ramona's 7 Evil Exes!" ("Olaf-: Ah, excellent film ça ArnY"))
 (#t "2011-09-16" "salut les conspirationistes pro Bush!" ())
 (#t "2011-09-25" "salut les morpions grouillants sur les hémorroides d'une pute lepreuse et tuberculeuse plein d'herpès" ("Craglu: ça manque de mucoviscidose" "ArnY: pas assez purulent, mon fils" "companion_cube: avec ArnY, refaites le plein de fraîcheur!"))
 (#t "2011-10-05" "salut les naines diarhéiques obèse à poils ras" ("[Juste avant]" "SK: la foule en folie scande le nom d'arny" "[Juste après]" "SK: les filles au premier rang font tomber le maillot"))
 (#t "2011-10-06" "salut pauvres geeks en pleur suite à la mort de leur idole" ())
 (#t "2011-10-09" "salut les étalons bien membrés aux corps d'athlètes musclés et bronzés luisant et à la poitrine digne de lolo ferrari" ("Cafai: erf.. je ne me reconnait pas, je remplis tout sauf le dernier critere"))
 (#t "2011-10-10" "salut les pouffes molles et flasques" ("Feufochmar: ArnY: note du message de bonjour : 4,3 / 10" "***SK s'attendait a des sabotiers savoyards" "***ArnY est fatigué"))
 (#t "2011-10-21" "salut les nabots mongols suceurs de queues de babouins obèses" ("companion_cube: ArnY: c'est ambigu, qui est obese ?" "Balise: les queues."))
 (#t "2011-10-26" "salut les ARRRRGGG qui GRRRRRRRRRRR du PFFFFFFFF" ("MFX: salut vieille quenille"))
 (#t "2011-11-01" "salut les fisteurs anonymes rassemblés en colloque à la Fistinière." ("Craglu: ça s’écrit Finistère" "ArnY: fait pas l'ignorant, t'as encore ton badge sur ta poche!"))
 (#t "2011-11-10" "salut les bougres de crème d'emplâtre à la graisse de hérisson!" ("***Olaf- badigeonne ArnY de graisse de phoque."))
 (#t "2011-11-14" "salut les suce-pines!" ("Cafai: Y'en a pas un qui bronche, pourtant il y en a !" "Olaf-: C'est que celle d'ArnY est trop grosse, on a peur." "Sigma: Olaf-: j'ai pas un microscope aussi performant que le tien" "Cafai: ArnY va le regreter, il va se retrouver avec un microcope bloque dans son uretre, ca doit piquer"))
 (#t "2011-11-30" "salut les lombrics vermoulus du bout" ("companion_cube: salut ArnY" "rbs: il parle aux lombrics de dibalo" "ArnY: dibalo fait du compost avec des lombrics ?" "Zluglu: non, avec les poubelles de la ratp"))
 (#t "2011-12-03" "salut les résidus de fond de capotes percées" ())
 (#t "2011-12-14" "salut, je vous pète à la tête!" ())
 (#t "2011-12-19" "salut les folles accros à la saucisses" ())
 (#t "2012-01-04" "salut les nonagénaires pervers déguisés en barbies pour appater les petits enfants sur la place de l'église à l'heure du déjeuner" ())
 (#t "2012-01-09" "salut les nabots nonagénaire nains noirs nus à nibards nazes non animés de nobles noms" ("SK: tu maitrises l'alitération" "Olaf-: pas la consonance, c'est dommage" "ArnY: Olaf-: teuh teuh teuh, soit pas jalouse"))
 (#t "2012-01-10" "salut les abonnés SFR qui pleurent" ("rbs: ah, c'est mes parents ça" "rbs: pourtant je les avais prévenu..."))
 (#t "2012-01-27" "salut les petits potames flatulant dans l'eau du bain!" ())
 (#t "2012-02-03" "salut les baleines à laine à l'aisne à l'haleine malsaine dans l'Aisne" ())
 (#t "2012-02-06" "salut les ploucs" ())
 (#t "2012-02-19" "salut les globiboulmen!" ("companion_cube: salut les danseuses étoiles de soixante ans"))
 (#t "2012-03-02" "salut les gros globuleux des ovaires" ("Balise: ai-je les ovaires globuleux" "Balise: c'est une bonne question"))
 (#t "2012-03-15" "salut les mongols baveux rampants comme des loches" ("***SK slappe ArnY" "***dcc slappe ArnY" "***ArnY jète un bouquin à SK"))
 (#t "2012-04-02" "salut les trannies molles du gland" ("SK: salut le tArnY mou du gland"))
 (#t "2012-04-04" "salut les boudins mal cagués" ())
 (#t "2012-05-06" "salut les nanards" ())
 (#t "2012-05-10" "salut les tafioles" ())
 (#t "2012-06-04" "salut les mous du genou" ())
 (#t "2012-06-06" "salut les dilatés du bas du dos!" ("Olaf-: Salut le dilaté de l'anus." "Olaf-: Avoue que bas du dos, c'est pas terrible..." "rbs: on la fait pas à Olaf-"))
 (#t "2012-06-08" "salut les désanussés ensanglantés" ())
 (#t "2012-06-19" "salut les big fat ugly mongoliens albinos" ())
 (#t "2012-06-20" "salut les déménageurs chauves en tutus en train de se faire un bbq sur les champs élysées" ("rbs: et éleveurs de poules" "ArnY: non, par contre zoophiles, oui" "Zluglu: salut le fan des Rita Mitsouko"))
 (#t "2012-06-21" "salut les nymphos naines bronzant au rayon rotisserie de carrefour" ("guitou: on peut bronzer au rayon rotisserie ?" "***guitou note"))
 (#t "2012-07-04" "dilatés de la rondelle!" ())
 (#t "2012-07-06" "salut les grouillants vérmoulus" ())
 (#t "2012-07-11" "salut les coprophages rassasiés" ())
 (#t "2012-07-15" "salut les étalons" ("Olaf-: C'est vrai que je suis bien membré." "Olaf-: ArnY: Salut le poulain." "ArnY: c'est vrai que j'ai gout de chocolat et que je suis en poudre"))
 (#t "2012-07-16" "salut les amputés de la colonne vertebrale" ("[Juste avant]" "ArnY [Edison@bow.before.me.for.i.am.r00t.fr] a rejoint le salon." "ArnY: plop, j'ai besoin d'un petit coup de main, il y a des gens ici qui ont un hébergement mutualisé chez OVH?" "tripa: seulement si tu nous salues" "rbs: c'etait ça le salut, il nous a traité de clients d'OVH"))
 (#t "2012-07-17" "salut les zizi tout mous" ("ArnY: +s" "Olaf-: tu vas nous le durcir ?"))
 (#t "2012-07-22" "salut les accros du sexe anal mal embouchés" ())
 (#t "2012-07-24" "salut les courts sur pates avec le bout de la queue toute rugueuse" ())
 (#t "2012-07-31" "salut les gorilles amateurs de naines à poil ras" ("Olaf-: ArnY: lapines ?" "ArnY: Olaf-: stoi la pine" "Olaf-: au moins j'en ai une \\o/"))
 (#t "2012-08-15" "salut les résidus d'hémoroides de porcs" ())
 (#t "2012-08-18" "ahem... compiz a mangé mon super greeting de compet qui mentionnait des hommes musclés et des animaux dans une scène très chaude :(" ("rbs: tututut, on nous la fait pas"))
 (#t "2012-09-02" "salut les motherfucking batshit crazy cocksuckers" ("Olaf-: I prefer licking" "ArnY: Olaf-: espèce de shitball licking motherfucker" "companion_cube: motherlicker*" "dibalo: c'était pas cocklicker ?" "companion_cube: en y repensant, cocksucker et motherfucker c'est assez incompatible, non ?" "dibalo: bah non" "dibalo: s'il y a papa dans la chambre de maman, on peut faire plaisir à tout le monde" "ArnY: nan, shitball licking motherfucking ass raming brainless git"))
 (#t "2012-09-06" "salut les gougnafiers!" ())
 (#t "2012-09-10" "je vous pète à la tête!" ())
 (#t "2012-09-17" "salut la bande de" ())
 (#t "2012-09-19" "salut les vieux éboueurs roux en slip kangourou léopard fumant à la pipe du crotin d'ane corse à Pigale" ())
 (#t "2012-09-24" "salut les dilatés de la chambre à air" ("Palats: plffffrrrrfffff" "Simplet: avec ou sans trace de pneu ?"))
 (#t "2012-09-26" "salut les mous du bout!" ())
 (#t "2012-09-28" "salut mes meilleurs amis du monde! je vous <3!" ("companion_cube: fake"))
 (#f "2012-09-30" "***ArnY vous morve à la raie!" ())
 (#f "2012-10-11" "salut femmes!" ())
 (#t "2012-10-15" "salut les frelatés de la cavité nauséabonde" ("Olaf-: moui, 3/10" "ArnY: tu es dur, Olaf-, cmb!"))
 (#t "2012-10-16" "salut les vieux vieux routiers albinos obèses se triturant la frite sur le bord du périf parisien" ("Cafai: et y'en a certainement"))
 (#t "2012-10-17" "salut les malformés de l'anus en trompette!" ("***Olaf- a l'anus qui trompette ce soir"))
 (#t "2012-10-21" "salut les bouchers mongols naturistes" ())
 (#t "2012-10-29" "salut les daltons petomanes en tournées mondiale dans les toilettes publiques!" ())
 (#t "2012-10-30" "salut les lombrics aux langues languissantes" ())
 (#t "2012-11-15" "salut les moldus ramolos de l'amalgame!" ())
 (#t "2012-12-09" "salut bandes de sales trolls gluants de placenta" ())
 (#t "2013-01-21" "salut les nains de jardin" ())
 (#f "2013-01-23" "***ArnY slaps le chan" ("***Olaf- gruicks at ArnY" "***Simplet proute sur ArnY"))
 (#t "2013-01-28" "salut les residus de grand n'importe quoi" ())
 (#t "2013-01-29" "salut les léproïdes degoulinants" ())
 (#t "2013-02-04" "Salut les amateurs de trous de balle à la béarnaise!" ("[Juste avant]" "***dibalo slappe ArnY qui oublie la politesse" "[Juste après]" "ArnY: mieux?" "Olaf-: miam" "Olaf-: 7/10" "dibalo: mieux !"))
 (#t "2013-02-05" "Salut les petits cupidons blonds tout bourrelés virevoletant comme tels des papillons de lumière dans l'azur" ())
 (#f "2013-02-10" "bonne année!!!" ("Olaf-: joyeux noËl"))
 (#t "2013-02-11" "salut les naines rousses à forte poitrine et aux tétons tout rapés" ())
 (#t "2013-02-15" "salut les nazes nabots narcissiques nains nus!" ("companion_cube: j'aime pas les alliterations en 'a'" "ArnY: companion_cube: tant mieux!"))
 (#t "2013-02-18" "salut les slips pleins de boue corporelle!" ("Olaf-: miam" "Olaf-: 8/10" "ArnY: nickel pour ceus qui sont en train de manger!" "ArnY: ceux" "ArnY: servez vous un grand bol de boue corporelle!" "serianox: boue corporelle, ça vaut pas fromage de bite"))
 (#t "2013-02-26" "salut les vieilles kekettes de biquettes" ("Olaf-: ah pas mal" "Olaf-: 6.5/10" "dibalo: salut !" "rbs: ah, dibalo s'est senti visé" "Olaf-: ben les biquettes, ça lui rappelle le larzac tout ça" "dibalo: exactement !"))
 (#f "2013-02-27" "dibalo?" ("dibalo: oui ?" "dibalo: ah, c'est l'insulte de greeting ?" "Olaf-: ouais" "Olaf-: je suis outré"))
 (#t "2013-02-28" "salut les ruines moisissantes de la race inferieure" ("***Olaf- est de l'espèce supérieure" "ArnY: que tu crois"))
 (#t "2013-03-06" "salut les presse-couilles de cariboux" ())
 (#t "2013-03-12" "salut lulu les abruti titi" ())
 (#t "2013-03-19" "Salut les tronches de tartifelette pestiférées et purulantes, votre odeur s'accorde au ravage qui vous sert de visage!" ())
 (#t "2013-04-02" "salut les globuleux de la rate" ("Balise: oi, ma rate se porte très bien, d'abord"))
 (#t "2013-04-03" "salut les morveux de l'urète" ())
 (#t "2013-04-04" "non, je crois, je vous l'annonce, je ne m'abaisserai pas à vous saluer! Votre intelligence semblant être inversement proportionnelle à votre odeur rien que l'idée d'ouvrir la bouche pour me rabaisser à vos conventions social me donne envie de vomir!" ("companion_cube: ponctuation why u not here" "ArnY: companion_cube: elle n'a pas voulu se rabaisser à ton niveau et a préférer aller passer ces congés dans un goulag en corée du nord à la place!"))
 (#t "2013-04-08" "salut les petits papillons de rosée flottant de l'aurore silencieuse d'une douce prairie d'été" ())
 (#t "2013-04-17" "salut les moches" ())
 (#f "2013-04-18" "salut mesdames" ())
 (#t "2013-04-24" "salut les fientes humaines" ("rbs: salut Frank Walton"))
 (#t "2013-05-16" "salut les ablationnés testiculaires" ())
 (#f "2013-05-17" "mesdames..." ())
 (#t "2013-05-21" "salut les gérontologue urophiles grecs et longitilignes!" ("***Olaf- pisse sur ArnY" "Olaf-: t'as raison, j'aime ça !"))
 (#t "2013-05-28" "salut les pantysniffers!" ())
 (#t "2013-05-29" "salut les gay lurons!" ("Olaf-: salut le luron triste" "companion_cube: salut l'hétéro obsolète"))
 (#t "2013-05-30" "salut les glouglouteurs de poireaux" ("Zluglu: glouglouTAteurs, stp" "rbs: s/poireaux/bieres/"))
 (#t "2013-06-03" "salut les moules frites en moule bites" ("bearclaw: tu la gardais pour une grande occasion celle là? On fête quoi?"))
 (#t "2013-06-10" "salut les déboucheurs de moules" ("Olaf-: ArnY: la moule de ta femme est bouchée, je viens la déboucher ?" "ArnY: démoules qui tu veux, mais ma femme n'a pas besoin de toi"))
 (#t "2013-06-11" "salut les homéopathes grecs" ())
 (#t "2013-06-12" "salut glands mous" ())
 (#f "2013-06-14" "j'etais en train de bouquiner quand, soudainement, je me suis retrouvé dans le salon avec faire de l'IRC. Qui m'a invoqué?" ("[Juste avant]" "Zluglu: invocation réussie\xa0!" "***Zluglu high-fives Simplet"))
 (#f "2013-06-21" "salut mongoloïdes" ("Olaf-: moui, 2/10"))
 (#t "2013-06-23" "salut les grouillots" ())
 (#t "2013-06-24" "salut les duchmols" ())
 (#t "2013-06-25" "salut les marmottes prostituées accros à la tisane de pneu" ())
 (#t "2013-06-26" "salut les épluchés du gland" ())
 (#t "2013-07-01" "salut les Bills et les Steves" ("Olaf-: salut Robert" "rbs: Robert Bull, ou Thomson ?" "***ArnY pensait plutot à Larry qu'à Robert" "ArnY: Larry Elison, bien sur"))
 (#t "2013-07-03" "salut les globuleux de la prostate" ())
 (#t "2013-07-04" "tarbanac de criss d'ostie!" ())
 (#f "2013-07-08" "m'sieurs dames" ("companion_cube: vieille branche"))
 (#t "2013-07-09" "salut les gnogologogoloïds!" ())
 (#t "2013-07-14" "salut les Cruchots et autre Le Glaude!" ())
 (#t "2013-07-16" "salut les nabogoloïds" ("Olaf-: ah pas mal" "Olaf-: 8/10"))
 (#t "2013-07-18" "salut les boeufs accros à la paillette" ("Zluglu: stoi la vache folle"))
 (#t "2013-07-24" "salut les couilles de tétards végétatifs attrofiés!" ())
 (#f "2013-07-26" "happy sysadmin daym" ("ArnY: -m + !" "Zluglu: stoi" "ArnY: yep!" "Olaf-: moui, 1/10 ArnY !"))
 (#t "2013-07-31" "salut les intoxiqués de l'anulingus" ("Olaf-: tu aimes qu'on te chatouille la rondelle quand tu bouquines ArnY ?" "ArnY: je ne vois pas ce qui te fait penser à ça, sale pervers!"))
 (#f "2013-08-01" "honk honk" ())
 (#t "2013-08-03" "piou piou les lombrics" ("dibalo: mais euh !" "dibalo: laisse mes lombrics tranquille !" "Olaf-: ils mangent ton caca au moins !"))
 (#t "2013-08-07" "salut les belles créatures féminines dotées d'un membre phalique hors normes" ("Olaf-: salut le transsexuel brésilien"))
 (#t "2013-08-08" "salut les furoncles forniquant sur le cul d'une vache!" ())
 (#f "2013-08-14" "prout prout" ("rbs: ArnY: comme la connec de Xanthor"))
 (#t "2013-08-27" "salut les vils couillus" ())
 (#t "2013-08-29" "salut les mongols non newtoniens!" ("rbs: c'est pas ici"))
 (#f "2013-08-30" "bow before me for I am r00t.fr again!" ("rbs: ah, c'est mieux" "Olaf-: F34R!¡"))
 (#f "2013-09-08" "prem's" ("Olaf-: fake!"))
 (#t "2013-09-09" "salut les globuleux" ("companion_cube: salut le phagocyte"))
 (#t "2013-09-10" "salut les ramonés du tunnel malodorant" ("rbs: ah, ArnY pour une fine analyse de la situation" "ArnY: rbs: de la merde moins chère, mais toujours trop chère et de la merde super chère"))
 (#t "2013-09-12" "salut les cariés de la glotte" ("Olaf-: salut le cariant de la glotte" "Olaf-: le cas riant ?"))
 (#t "2013-09-13" "salut les tondus du lobe" ("Olaf-: ArnY: salut le tendu du gland" "ArnY: Olaf-: salut le raclé de la prostate"))
 (#t "2013-09-16" "salut les rapeux du colon" ())
 (#t "2013-09-18" "salut les gondolés de la rate" ())
 (#t "2013-10-01" "salut les golmons mormons" ())
 (#t "2013-10-06" "guili guili m'sieurs dames" ())
 (#f "2013-10-09" "mesdames" ("Olaf-: mademoiselle" "dibalo: messieurs" "ArnY: amis à 4 pattes" "dibalo: amis 3 pattes cassées" "ArnY: ca doit litterallement pas courrir les rues..."))
 (#t "2013-10-10" "salut les lèches boules" ("Sigma: <3 les sorbets pomme/poire"))
 (#t "2013-10-14" "salut les crochus du Boukistan" ("Olaf-: ArnY: au moins il se tend le notre !"))
 (#t "2013-10-15" "salut les mousseux de la glotte" ("***rbs ne comprend pas la vanne d'ArnY" "Olaf-: il va faire mousser son zizi dans ton bec et tu vas vite comprendre" "dibalo: rbs: il dit que t’as la rage"))
 (#t "2013-10-16" "salut les fracturés du ciboulot!" ())
 (#t "2013-10-17" "salut les glougloutés de la tige!" ())
 (#t "2013-10-20" "salut lulu les cretins tintin" ("***Olaf- lance un lala sur ArnY pinpin"))
 (#t "2013-10-22" "salut les crottés de la moustache" ("rbs: c'est le risque avec les balais-brosse"))
 (#t "2013-10-29" "salut les dévissés du gland" ("***Olaf- revisse ArnY"))
 (#f "2013-11-04" "prem's" ())
 (#t "2013-11-10" "salut les vieilles biques qui puent du bec" ("sk: yop la biloute"))
 (#t "2013-11-12" "Salut les naines a poils ras" ("dibalo: salut la naine poilue"))
 (#t "2013-11-14" "Salut les naines difformes" ("companion_cube: tu as vraiment une prédilection particulière pour les naines :)"))
 (#f "2013-11-17" "Prem's" ())
 (#t "2013-11-21" "Salut les bouseux du jeudi" ())
 (#f "2013-11-24" "Prems!" ("[Heure: 03:55:49]" "Feufochmar: zut, j'allais dire derns" "ArnY: Mwhuahaha"))
 (#f "2013-11-25" "Hey y'all!" ("Balise: fais gaffe, tu prends l'accent"))
 (#t "2013-11-26" "Salut les nabots" ())
 (#f "2013-11-27" "Prem's" ("companion_cube: deuz" "Feufochmar: derns"))
 (#t "2013-12-09" "salut les naines à poil ras" ())
 (#f "2013-12-14" "prem's!" ("rbs: encore !" "ArnY: bah oui, je suis un bon, moi!" "Olaf-: t'es endurant" "Olaf-: 2 fois dans la même journée !" "rbs: ouais, mais prems à chaque fois, c'est pas très gallant" "Zluglu: PREMS"))
 (#f "2013-12-15" "prem's!" ("Feufochmar: derns!"))
 (#t "2013-12-19" "salut les pignouffs" ())
 (#t "2014-01-01" "salut les gronaz" ("guitou: salut le tout pourri" "ff: pareil" "ArnY: et surtout comptez pas sur moi pour vous souhaiter une bonne année"))
 (#t "2014-01-02" "salut les vieux albanais tout rugeux" ())
 (#t "2014-01-03" "salut ruminants amateurs de félins!" ("dibalo: moooo"))
 (#f "2014-01-05" "salut g" ("ArnY: errr" "ArnY: bon, ca suffira pour ce matin, je vais pas me faire chier à retaper mon \"salut\"" "Balise: \"surtout pour une telle bande de nazes\"" "ArnY: oui, c'etait implicite, voyons" "Olaf-: ça va de soi"))
 (#t "2014-01-08" "salut les dompteuses de slips" ("ff: stoi"))
 (#t "2014-01-11" "salut les naines à poils ras" ("Olaf-: ça t'excite les poils ras" "ArnY: pas de poil du tout c'est mieux"))
 (#t "2014-01-13" "salut les pestiférés des muqueuses" ("***dibalo frotte sa muqueuse sur ArnY" "ArnY: oh noes!" "ff: en public..." "ArnY: et tout nu!"))
 (#t "2014-01-14" "salut les enturbanés du kiki!" ("Olaf-: kiki taliban toi même !"))
 (#t "2014-01-15" "salut mes gentils copains!" ("Oulaffe: ArnY 0.5/10 ! Nullissime !" "ArnY: comme ton nick" "Olaf- a rejoint ce canal" "Olaf-: Ouais, Olaf- smieux" "Oulaffe a quitté ce canal (\"Bye\")" "***Feufochmar se demande ce que cache ArnY. Il n'est pas aussi aigri que d'habitude, c'est louche."))
 (#t "2014-01-16" "salut les broutes choucroutes" ("katyucha: non, je suis dans le pays des quiches, pas des choucroutes" "ArnY: ouais, mais broute quiche, j'ose pas imaginer ce que c'est au sens figuré"))
 (#t "2014-01-17" "salut les fistés aux gants de crin" ("Zluglu: stoi le gant de crin"))
 (#t "2014-01-18" "salut les mals branlés de la glote" ())
 (#t "2014-01-19" "salut les vieilles berniques" ("companion_cube: salut l'amateur de naines unijambistes" "Zluglu: salut le hedgehog"))
 (#t "2014-01-23" "salut les coloscophobes movitophiles!" ("rbs: c'est toi le movito" "ArnY: ah oui tiens, c'est vomitophiles que je voulais dire" "ff: suis pas dislexophile perso"))
 (#t "2014-01-27" "salut les constipés du poireau" ("***guitou chie sur ArnY" "ArnY: hola, on se calme, je parlais de constipation du poireau, hein!" "ArnY: toujours à faire dans le scato, ici... pfff"))
 (#t "2014-01-28" "salut les gondolés de la tige" ())
 (#t "2014-01-29" "salut les glouloutés du popol" ("rbs: ArnY s'est encore trompé de chan"))
 (#t "2014-01-30" "salut les dévissés des testicules" ())
 (#t "2014-01-31" "salut les pompés de la canalisation!" ())
 (#t "2014-02-03" "salut les bourgeonnés de la prostate!" ())
 (#t "2014-02-04" "salut les zigzagués du conduit d'évacuation" ())
 (#t "2014-02-06" "salut les décalaqué du ciboulot" ("ArnY: +s"))
 (#t "2014-02-07" "salut bourssouflés de la perche" ())
 (#t "2014-02-11" "salut les gondolés du mat" ("Olaf-: c'est pas d'notre faute"))
 (#t "2014-02-12" "salut les muppets qui puent du bec" ())
 (#t "2014-02-14" "bonne saint valentin à tous les célibataires du chan!" ("serianox_: ArnY: grrr" "ArnY: yay! :)" "rbs: ArnY: pour nous c'est peinard" "rbs: c'était le soir où faut pas aller au resto" "rbs: potage, ordi et au lit"))
 (#t "2014-02-18" "salut les champignaciens" ())
 (#t "2014-02-19" "salut les naines purulentes" ("Balise: salut le vieux con" "Balise: (je fais pas dans l'original)" "***Olaf- lance du pus sur ArnY" "Olaf-: \"pop le bouton\""))
 (#t "2014-02-22" "salut les gentils geeks qui hantent ce chan comme des berniques sur un rocher plein de mazout" ("***rbs n'est pas un geek" "rbs: d'après la définition de TF1" "ArnY: c'est quoi la definition de tf1?" "rbs: en fait j'en suis pas sur, vu que je reçois pas la chaine"))
 (#f "2014-02-23" "mesdemoiselles..." ())
 (#t "2014-02-27" "salut les troufions!" ("katyucha: oui truduc" "rbs: katyucha s'est fait piéger"))
 (#t "2014-02-28" "salut les vieilles cagouilles toutes frippées" ("rbs: tiens, tu t'es mis au québequois" "rbs: ou ça y ressemble, en tous cas" "Zluglu: cagouilles ? strop pas québequois" "ArnY: nan, c'est plutot sudois"))
 (#t "2014-03-01" "prem's les vieux zizi tous pourris" ("Olaf-: nécrophile" "guitou: stoi"))
 (#t "2014-03-06" "salut les nains plats" ("dibalo: salut le géant à nichons"))
 (#t "2014-03-07" "salut les tordus de la caboche" ())
 (#t "2014-03-10" "salut les absents lors de la distribution de cerveau!" ("rbs: chez nous c'est un équipement de série" "ArnY: vous avez le modèle déféctueux, il a été remplacé en standard, mais vous etiez absent!"))
 (#t "2014-03-11" "salut les gondolés du vermicelle" ("rbs: c'est pas ici" "ArnY: meuh si" "rbs: ici c'est les bras cassés et les boiteux"))
 (#t "2014-03-12" "salut les moisis de l'urète!" ())
 (#t "2014-03-13" "salut les gos boulous tout frippés" ("katyucha: ArnY: salut le gras du cerveaux" "katyucha: -x"))
 (#t "2014-03-18" "salut les pouilleux de la glotte" ())
 (#t "2014-03-19" "salut turlututu, poil au..." ("dibalo: merlu ?" "***ArnY a été interrompu dans son élan par sa femme qui lui reprochait d'avoir mis un cube dans le bac à jouet au lieu de le mettre dans le bac à cube!" "ArnY: dibalo: trou du cul" "dibalo: ah :) oué, j'en ai"))
 (#t "2014-03-24" "salut les gros bouliboulas!" ())
 (#t "2014-03-25" "salut les gadougadous" ("rbs: ah, voilà un expert"))
 (#t "2014-03-26" "salut les molomolos" ())
 (#t "2014-03-27" "salut les glougloutés des bourses" ())
 (#t "2014-03-30" "salut %%randomAdjective%% %%RandomNoun%% !" ())
 (#t "2014-03-31" "salut les mousseux du bulbe" ("katyucha: Salut a toi l'homme de l'Ouest sauvage"))
 (#t "2014-04-02" "salut les soustendu de l'asperge" ("ArnY: +s" "katyucha: salut l'homme qui voit le soleil en dernier"))
 (#f "2014-04-03" "salut les" ("ArnY: segmentation fault"))
 (#t "2014-04-04" "salut les édentés du colon!" ("dibalo: t’as des dents au colon ?" "rbs: il parle aux têtes de fion, là" "ArnY: faut pas chercher à trop analyser, c'est un langage imagé, voyons!" "rbs: c'est pas le genre de la maison"))
 (#t "2014-04-07" "salut les décerébrés" ())
 (#t "2014-04-08" "salut les pekno-dilato!" ())
 (#t "2014-04-09" "salut les... ewww, degueu!" ("companion_cube: geeeee"))
 (#t "2014-04-10" "salut les mous du bout" ("Zluglu: salut le bout du mou" "***Zluglu est mauvais en contre-tripa"))
 (#t "2014-04-11" "salut les suce-nigauds" ())
 (#t "2014-04-13" "salut les anomalies sexuelles!" ("Simplet: salut l'ordinairement normal"))
 (#t "2014-04-15" "salut les rabotés du piquet de tente!" ("Balise: non moi je suis juste rabotée de l'auriculaire gauche" "Balise: (me suis râpé le doigt en râpant du cheddar avant hier, ça fait mal)"))
 (#t "2014-04-16" "salut les emulsionnés de la rate!" ())
 (#t "2014-04-17" "salut les petits tirlipinpons!" ("rbs: à l'arc"))
 (#t "2014-04-23" "salut les mongoloïdes chibreux morpho-phalliques" ())
 (#t "2014-04-25" "salut les broutbrouts" ())
 (#t "2014-04-26" "salut les cagouilles en string" ())
 (#t "2014-05-07" "salut les punks à pingouin!" ())
 (#t "2014-05-12" "salut les tarlouloutes à barbiroutes!" ("rbs: c'est pas ici"))
 (#f "2014-05-13" "tadam! le ArnY!" ())
 (#t "2014-05-15" "salut les pustulés du bulbe!" ())
 (#f "2014-05-21" "djû-djû!" ())
 (#t "2014-05-25" "bonne fête à toutes les mamans du chan!" ("companion_cube: stoi" "ArnY: à personne, quoi" "guitou: je peux demander a elmiree de se connecter"))
 (#f "2014-05-26" "eviv bulgroz!" ("guitou: YnrA !"))
 (#f "2014-06-02" "piou piou" ("guitou: pan pan"))
 (#t "2014-06-03" "salut les cartonnés du conduit obscure!" ("rbs: salut l'ex-futur-breton" "dibalo: NANTES EN VENDÉE !"))
 (#t "2014-06-05" "salut les routiers qui chient dans le fossé!" ())
 (#t "2014-06-07" "salut phalus d'enfoirés enfarinés" ("dibalo: salut" "companion_cube: c'est pas phalli au pluriel ? ^^" "dibalo: http://www.academie-francaise.fr/sites/academie-francaise.fr/files/rectifications_1990.pdf page 12, point 7." "ArnY: merci maitre capellibalo"))
 (#t "2014-06-10" "salut les frelatés de la colonie intestinale" ())
 (#f "2014-06-12" "prooooooOOOOOooooooOOOOOooooooot proot" ("rbs: y a de l'ambiance chez ArnY" "ArnY: je suis là pour ca, voyons!"))
 (#f "2014-06-17" "Boooooooooooooooooooooooooooooooo" ("ArnY: (boo long)"))
 (#t "2014-06-18" "bien le bonsoir bandes de couillus qui puent" ("katyucha: salut tarlouse"))
 (#t "2014-06-23" "salut les êtres primitifs à l'intellect déficient" ())
 (#t "2014-06-24" "salut les rikikis du spaghetti" ())
 (#t "2014-06-25" "salut bande de mugles sans baguette!" ())
 (#f "2014-06-26" "pouf pouf" ("Sigma: stoi ?"))
 (#t "2014-06-28" "salut les lèches bouboules" ())
 (#t "2014-07-07" "salut les incapacités de l'intellect au gland hypertrophié!" ("ArnY: je vous insulte poliment et personne ne répond, vous êtes des malotrus!" "Zluglu: non, ici il n’y a que des malotrous" "Zluglu: tu devrais le savoir, t’es owner du chan, donc 1er concerné"))
 (#t "2014-07-08" "salut les tirbouchonné du tendon sexuel" ("Balise: brr" "***ArnY a oublié un s"))
 (#t "2014-07-15" "salut les golenouilles" ())
 (#t "2014-07-20" "salut les gras du menton!" ("Simplet: bonsoir le mou du scrotum"))
 (#t "2014-07-28" "salut les vieilles serpillères" ("katyucha: salut le maitre du web"))
 (#f "2014-07-29" "plipontron!" ())
 (#t "2014-07-29" "piou piou les nabots" ())
 (#t "2014-07-30" "salut les moussus de la perche" ("newnick: pan!" "ItsaMeQuacko: salut le pouchu de la messe !" "ArnY: ItsaMeQuacko: elle est nulle ta contreprouterie"))
 (#t "2014-07-30" "salut les vampires nymphomanes suceurs de queues" ("rbs: c'est pas ici, monsieur" "bcollet: Sarah Connor ?"))
 (#t "2014-08-01" "salut les disciples ramolis de l'Eglise d'Archerie du Grand Vizir Zluglu 1er" ("***ItsaMeQuacko n'est donc pas concerné" "Olaf-: tu salues que rbs quoi" "ItsaMeQuacko: feur" "Olaf-: mule1"))
 (#t "2014-08-02" "salut les fendues de l'anus" ())
 (#t "2014-08-03" "salut les joyeux phoques à la queue brune et malodorante!" ())
 (#t "2014-08-07" "salut les nains de jardin à la bite rude" ())
 (#t "2014-08-07" "salut mes minions!" ())
 (#t "2014-08-08" "salut les déboités du kiki" ())
 (#t "2014-08-16" "salut les vieux dilatés" ("serianox_: tes insultes ne m'atteignent pas, j'ai Money for Nothing dans les oreilles"))
 (#f "2014-08-19" "miaou?" ("***rbs jete un seau d'eau" "***ItsaMeQuacko jette des graviers" "ItsaMeQuacko: seau d'eau avec graviers pour ArnY\xa0!" "ArnY: yay! rock bucket challenge!"))
 (#t "2014-08-20" "salut les crottés du gland mou" ("ArnY: z'ai bien dis du gland mou et pas du glos mou! soyons glaire!" "ArnY: glairs, pardon"))
 (#t "2014-08-21" "salut les nincompoops" ("ItsaMeQuacko: Salut le wombat de combat"))
 (#t "2014-08-23" "re les cyclistes nudistes" ())
 (#t "2014-08-24" "salut les dégazés du trou sombr" ("ArnY: e" "Zluglu: stoi" "rbs: Zluglu c'est plutôt \"Fire in the hole\""))
 (#t "2014-08-25" "salut les lombrics en érection au milieu d'une salle de cinéma X" ())
 (#t "2014-08-26" "salut le nouveau gouvernement trop à droite pour la gauche et trop à gauche pour la droit!" ("ArnY: e"))
 (#t "2014-08-27" "salut les déféqués respiratoires!" ("[Juste avant]" "Zluglu: ArnY : salut le mangeur de vomi réchauffé à la poëlle !"))
 (#t "2014-08-28" "salut les net-bouseux !" ())
 (#t "2014-08-30" "salut les castors à l'halène de fouine morte" ("***Balise mord ArnY avec ses incisives surdéveloppées" "Zluglu: ça a des super incisives les fouines\xa0?"))
 (#t "2014-09-01" "bon, les nouilles, là... il est temps que vous serviez à qq chose! mettez-vous à pupper et aidez moi à resoudre mes zerpazoeiraàçri aà\"'éçr_ ezàfç_ sdfw xcv cxv de soucis!" ("ArnY: puppet!" "ArnY: pas de \"oui, mais moi je suis dev, c'est pas mon boulot\" parce que, hein, dev... uhuh, on sait tous que c'est pas un vrai métier" "ArnY: vous faites du dev juste parce que les admins sont trop occupés à faire le vrai boulot et qu'ils vous laissent des miettes" "***bcollet est ingénieur-plombier il peut pas t'aider"))
 (#t "2014-09-06" "salut les linuxiens du samedi" ())
 (#t "2014-09-07" "plop, vous avez recu votre avis d'imposition?" ())
 (#t "2014-09-09" "salut les Apple fanboys" ())
 (#t "2014-09-12" "salut les vils brequins!" ())
 (#t "2014-09-14" "salut les nasty nachos" ())
 (#f "2014-09-14" "oink oink" ("dibalo: oink"))
 (#t "2014-09-16" "salut les routiers obèses et velus du dos!" ())
 (#t "2014-09-17" "salut les boos laids!" ("rbs: c'est pas ici" "ArnY: sarah connor?" "Zluglu: c’est à côté"))
 (#t "2014-09-18" "salut les grumeaux dans de la bouse de chameau" ())
 (#t "2014-09-25" "salut les vieux purulants" ("rbs: c'est celui qui dit qui l'est"))
 (#t "2014-09-29" "salut les bouchères à moustaches en combi spandex vert" ())
 (#t "2014-09-30" "salut les masseurs de lepreux" ("Zluglu: perdu, sk est parti"))
 (#f "2014-10-04" "proute" ("Zluglu: p.r00t.fr"))
 (#f "2014-10-05" "bouh! laids!" ())
 (#t "2014-10-05" "reuh les berniques" ())
 (#t "2014-10-06" "salut les petits mickeys" ())
 (#t "2014-10-07" "salut les gazeux" ("Zluglu: salut le terreux" "ArnY: gaz, terre, reste plus que la mer.. qui sera le merdeux?"))
 (#f "2014-10-11" "Mlles..." ("Zluglu: tiens, un vieux" "ArnY: Zluglu: on dit \"un sage\""))
 (#t "2014-10-13" "salut! je vous pête à la tête cordialement à grands coups de jets malodorants postillonants de matière fécale sur vos jolis minois" ("ArnY: et bon appétit!"))
 (#t "2014-10-15" "salut mes petits chéris!" ("Olaf-: salut strip-teaseur nain" "ArnY: à la queue démeusurée" "Olaf-: on dit micropénis"))
 (#t "2014-10-16" "salut les prolapsés" ())
 (#t "2014-10-17" "salut mes barbus plein de croutes" ("Zluglu: ArnY : stoi la croute barbue" "***rbs met du poulet dans sa barbe, plutôt que des croutes, c'est plus nourrissant" "Zluglu: des croutes de poulets ?" "Zluglu: eeek"))
 (#t "2014-10-27" "salut les marteaux dans la boite!" ("Olaf-: ma bite tape aussi dur qu'un marteau ArnY !" "ArnY: Olaf-: t'as un sacré coup de pelle^Wbite"))
 (#t "2014-10-29" "salut les plonkés du petits intestins" ("MFX: stoi"))
 (#t "2014-10-30" "salut les linuxoïds siamois" ())
 (#t "2014-11-12" "bon alors, harponné ou pas?" ("dibalo: non" "dibalo: (du moins si tu parles de ma vie sexuelle)" "ArnY: je parlais de la vie sexuel de Philae" "ArnY: +le"))
 (#t "2014-11-16" "debout! c'est l'heure de la messe!" ("Olaf-: qu'estce que tu fous sur irc !" "ArnY: je suis venu vous rappeler que c'est l'heure de la messe!"))
 (#t "2014-11-18" "salut la bande de vieux puduks pervers" ())
 (#t "2014-11-19" "salut les beaux apollons huilés à l'huile de vidange" ("DarkBruce: ça protège contre les UV"))
 (#t "2014-12-14" "salut les glouglouteurs de poireaux" ("rbs: ArnY: tu t'es encore trompé de chan" "ArnY: c'est fucking #linux ici ?" "rbs: c'est #linux tout court"))
 (#t "2014-12-26" "joyeux noel motherfuckers d'enfoirés" ("Zluglu: salut à toi l’encupafé\xa0!"))
 (#t "2015-01-01" "bonne année les mongols de Laponie!" ())
 (#t "2015-01-04" "salut les grands léchant mous" ())
 (#t "2015-01-06" "salut les ramonés de la glote" ())
 (#t "2015-01-12" "salut les vieilles loques imbibées" ())
 (#t "2015-01-13" "salut la chienlit!" ())
 (#t "2015-01-14" "bonsoir les gentils linuxiens!" ("Darkbruce: bonsoir grand maitre"))
 (#t "2015-01-21" "salut les écourtés du vermicelle" ())
 (#t "2015-02-01" "salut les pervs gluants" ())
 (#t "2015-02-09" "salut les bots en poudre" ())
 (#t "2015-02-12" "salut les grangrenés du bout qui crache" ())
 (#t "2015-02-14" "joyeuses saint valentin à tous les célibataires!!" ("rbs: c'est pas ici" "rbs: tu parles bien des célibataires qui sont la rose à la main à l'heure qu'il est ?" "***rbs se définirait plutot comme solitaire"))
 (#t "2015-02-16" "salut les demi-molles" ("Katyucha: salut demi dur"))
 (#t "2015-02-17" "salut les suces pets!" ())
 (#t "2015-02-18" "salut les disco-mongols!" ("rbs: ah c'est bien ici, salut"))
 (#t "2015-02-20" "salut les moto-crottes humaines" ("Zluglu: salut le sasquash déluré"))
 (#t "2015-03-01" "salut pauvres malheureux eteints de géantisme testiculaire!" ("Zluglu: stoi l’éteint"))
 (#t "2015-03-02" "salut les gobe-boules!" ())
 (#t "2015-03-07" "salut les schlingueux du clapet!" ("dibalo: oucou" "Zluglu: u eux oir a bite?" "Zluglu: merde, ite"))
 (#t "2015-03-09" "salut les barbibuls" ())
 (#t "2015-03-11" "salut les ptit mickeys" ("Zluglu: salut le cheval bipède" "ArnY: Zluglu: appeles moi simplement l'étalon comme tout le monde"))
 (#f "2015-03-12" "m'sieurs dames" ("Balise: m'sieur." "Alex: madam" "ArnY: sir" "Balise: ladies." "Alex: pussies!" "ArnY: gentlemen." "ArnY: motherfuckers"))
 (#t "2015-03-13" "salut les défoncés de la souflerie" ())
 (#t "2015-03-15" "salut les vieux moignons croustillants" ("Olaf-: salut le léprosé" "ArnY: seulement léprosé du bout!"))
 (#t "2015-03-26" "salut les mongols pouileux à poils roux" ())
 (#t "2015-03-27" "salut les petits nazillons tombés du nazinid!" ())
 (#t "2015-03-30" "salut les linuxoïds nains" ("rbs: y en a pas trop par ici" "rbs: par contre si tu cherches des archeroïds nains ou autres espèces, on a ça en stock"))
 (#t "2015-04-02" "salut les moumoules moimoisies" ())
 (#f "2015-04-13" "mamazelles..." ("companion_cube: demoiseau" "Zluglu: un moiseau" "Zluglu: deux moiseaux" "Zluglu: avec un X"))
 (#t "2015-04-17" "salut les naines à barbe!" ())
 (#t "2015-04-29" "salut les êtres non newtoniens" ("***Balise ondule" "***dibalo devient solide" "***ArnY pokes Balise pour vérifier" "***Balise particules" "ArnY: nan, t'es censée solidifier, comme dibalo" "***Balise devient un sabre laser"))
 (#t "2015-04-30" "salut les vilains spasmoïds globuleux" ())
 (#t "2015-05-01" "salut les blobineux" ())
 (#t "2015-05-05" "salut les vilains mal pinés" ("rbs: c'est pas ici"))
 (#t "2015-05-16" "salut les gros nazes nazis nuls et nus nazillant du nez" ())
 (#t "2015-05-23" "bien le bonjour Mes Soeurs" ("Zluglu: sœurs" "Zluglu: ArnY : sheuwesh gro\xa0!"))
 (#f "2015-05-25" "mesdames..." ())
 (#t "2015-05-26" "salut les vielles raclures de semelles de bottes" ())
 (#t "2015-05-31" "salut les déformés de la tronche" ())
 (#t "2015-06-01" "salut les granuleux de la tronche" ())
 (#t "2015-06-03" "salut les glouglouteux" ())
 (#t "2015-06-04" "salut bouseux de tout pays!" ("katyucha: salut des bouseux de l'est" "Olaf-: t'as déménagé dans ton chateau de boue ArnY ça y est ?"))
 (#t "2015-06-05" "salut les vieux zizis tous rabougris!" ())
 (#t "2015-06-06" "salut les gluants du gland!" ("rbs: c'est pas ici"))
 (#t "2015-06-08" "salut les grumeleux de la prostate" ())
 (#t "2015-06-14" "salut les mongololiens" ("rbs: c'est les linuxiens ici, à ne pas confondre"))
 (#t "2015-06-26" "salut les branlemoux jaunatres en string de fourrure!" ("katyucha: ah , j'ai pas eu ce ArnYtron ce jour" "ArnY: katyucha: l'ArnYtron me force à innover!" "katyucha: je me doute :) Tu devras vaincre la machine"))
 (#t "2015-06-30" "salut les braaaaaaaaaaaaah braaaaaaaaaaaaaah braaaaaaaaaaaaaaaaaaaaaaaaaaaaah" ())
 (#t "2015-07-01" "salut les loquedus mous du larfeuille!" ())
 (#t "2015-07-02" "salut les vieux boucs homos qui sucent des girafes chevrofiles" ("ArnY: ou chevrophile, l'orthographe n'est pas garantie" "Olaf-: bèèèèèèèè" "ArnY: plutot hmmmé hmmmmé"))
 (#t "2015-07-05" "salut les vieux sumos grecs à poils ras bodonnant de la paire de glotes pileuses" ("Zluglu: bodonnant ?" "ArnY: Zluglu: t'es sourd? j'ai dis BEUDONNANT!"))
 (#t "2015-07-06" "sallut les \"ah tiens, je suis connecté ici?\"" ("ArnY: salut les \"ah tiens, je suis connecté ici?\""))
 (#t "2015-07-07" "salut les sucreurs de rondelles à brosse dure!" ("Zluglu: ah non" "Zluglu: medium ici"))
 (#t "2015-07-09" "salut les réclures de vieux furoncles purulants" ())
 (#t "2015-07-11" "salut les furonculés!" ("Zluglu: salut l’énuclé !" "ArnY: eunuculé?" "Zluglu: non :)" "ArnY: c'etait pourtant bien trouvé!"))
 (#t "2015-07-13" "salut les ballonés du long tunnel ou la lumière ne brille jamais!" ())
 (#t "2015-08-16" "salut les vieux niakoué tondus au chalumeau!" ("Zluglu: salut à toi, fidèle utilisateur du arnytron"))
 (#f "2015-08-17" "bow before me for I am soon bow.before.me.for.I.am.r00t.fr !" ("Zluglu: bow before me for I am a mauviette44"))
 (#f "2015-08-18" "bow before me for why the fuck am I still not bow.before.me.for.I.am.r00t.fr ?!?" ())
 (#t "2015-08-19" "salut les vieux singes tout fripés dont l'haleine de dragon mort n'égale que la laideur de poux en pétrufaction!" ("Zluglu: :)" "Zluglu: he’s back !" "Zluglu: and he’s r00t.fr !" "ArnY: oh yeah baby!"))
 (#t "2015-08-20" "salut les merdouillus de la kekette molle!" ("katyucha: salut ArnY, inspiration de mon MOTD"))
 (#t "2015-08-21" "salut les enrhumés du gland phosphorescent!" ())
 (#t "2015-08-22" "salut les vieux cagueux tout rabougris du ouistiti" ())
 (#t "2015-08-24" "salut les globulés de la morve gout fraise et aux bras en forme de bouse!" ("Zluglu: salut à toi, fidèle plagieur de l’ArnYtron3000"))
 (#t "2015-08-25" "salut les naines inuits obèse accros à la glace au schtroumpf" ("Zluglu: stoi" "katyucha: zzzz" "katyucha: tu fais ça pour aider ArnYtron3000 ?"))
 (#t "2015-08-26" "salut les ragondins discos accrocs à la paillette!" ("katyucha: ArnYtron3000: génère" "ArnYtron3000: salut les golmons mormons" "ArnY: putain ArnYtron3000 me bat niveau originalité, je suis dégouté" "katyucha: ragondins discos !! plus original ça" "katyucha: Comme Kasparov et DeepBlue, désormais Arny doit se battre contre lui-même !!" "ArnY: :)"))
 (#t "2015-08-27" "salut les limaces chromées à double réacteurs en pate à modelée adeptes de curling nudiste" ("dibalo: c’est pas redondant limace et nudiste ?" "ArnY: non, il y a des limaces qui sont adeptent du curling en fourrure de muppet" "ArnY: je vous en parlerai un autre jour" "ArnY: adeptes"))
 (#t "2015-08-29" "salut les rates pelées du kazakstan en bikini fluo en train de tapiner sur les champs élysées" ("Balise: not bad" "ff: ouais y a de la référence culturelle" "Zluglu: ff : amateur de bikini fluo ?" "Zluglu: ArnY : comment il s’appelle déjà ? Borat ?" "Zluglu: c’est pas un bikini, et c’est pas fluo" "ArnY: :)" "ArnY: il était kazak Borat?" "ArnY: ah ouais"))
 (#t "2015-08-31" "salut les cuistos obèses enduits d'huile de vidange s'apprétant à danser le twist avec des otaries suisses en beton" ())
 (#t "2015-09-04" "salut les vieux grailleux du ciboulot" ("dibalo: salut, et bon anniversaire" "Olaf-: ah ouais, google m'a dit" "Olaf-: bon anniv à tous les 2 !" "Olaf-: (hier)" "ArnY: dibalo: ah ouais, c'etait mon anniv! merde!" "ArnY: dibalo: merci et à toi aussi du coup" "***ArnY pigeait pas pourquoi tout le monde lui souhait son anniv!"))
 (#t "2015-09-06" "salut les vieilles croutes d'acnée purulante du dos d'un vieux phoque obèse" ())
 (#t "2015-09-07" "salut les découénés funky de la préhistoire mongole" ())
 (#f "2015-09-09" "\"What if you could press with 3D Touch on your photos and this happened?\" The photos animate into video, called Live Photos. <-- Ca y'est!! Apple a enfin inventé la vidéo! ca va révolutionner les medias!" ("katyucha: Apple vient de créer le GIF" "katyucha: ArnY: tu sors" "katyucha: même pas un bonjour pour le ArnYtron" "katyucha: pfff" "ArnY: nan!" "Zluglu: remboursé !"))
 (#t "2015-09-10" "salut les vielles taupes embouteillées du canal obscure" ("[Juste avant]" "Zluglu: onoz" "Zluglu: un wild arny appears" "Zluglu: :genere" "ArnYtron3000: salut glands mous du bec" "[Juste après]" "Zluglu: ArnY 1 - 0 ArnYtron3000"))
 (#t "2015-09-11" "salut les accrocs de la sodomie à la biscotte (en fonte)" ("Zluglu: :genere" "ArnYtron3000: sallut les pisciculteurs scatophiles au chalumeau!" "Zluglu: 1 partout" "Olaf-: moi je préfère la sodomie au chalumeau" "Olaf-: c'est plus sport" "Zluglu: Olaf- : et les scatophiles à la biscote ?"))
 (#t "2015-09-12" "salut les gros enturbannés nus glissant sur le carrelage badigeonnés de mayonnaise au son de la  marseillaise" ("Olaf-: ah pas mal" "Olaf-: 8/10" "Olaf-: ArnYtron3000: génère" "ArnYtron3000: salut les cretins tintin" "ArnY: ahah, le nul!" "ArnY: I win!"))
 (#t "2015-09-14" "salut les merveilleux esthètes membrés comme des étalons dont les éfluves hormonales liquéfient toute représentante de la gente féminine!" ())
 (#t "2015-09-15" "salut les ptit zozios enculeurs de rapaces et cagueurs volants" ("Zluglu: CagueurVolant \\o/" "ArnY: il se reconnait! comme c'est mimi! :)" "Zluglu: non" "Zluglu: je ne pense pas que les o< chient en vol"))
 (#f "2015-09-17" "salut KK PD O Q KC K PT!" ("Zluglu :genere" "ArnYtron3000: salut les épluchés du crotin d'ane corse à l'intellect déficient" "ArnY: roh flute, il fait fort, là" "rbs: ouais, et ton salut va foutre le bordel dans l'ArnYtron3000" "Zluglu: faut dire que t’as fait faible…" "rbs: t'es en train de la saboter :)"))
 (#t "2015-09-18" "salut les mous du fondement rugueux à l'ouverture béante!" ())
 (#t "2015-09-19" "salut les limaçons portugais à fourrure verte electrisée et à la trique de porte drapeau" ())
 (#t "2015-09-21" "salut les vieux nains patatophiles hydrophobes" ("katyucha: salut à toi, l'homme de l'autre bord de la France" "ArnY: du bon bord, tu veux dire!" "katyucha: pas sur !" "ArnY: le bord salé!" "ArnY: pas comme le bord doux, qui n'est pas bon!"))
))
